name: quick_bank_ui
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  iconify_flutter: ^0.0.7
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/imgs/

  fonts:
    # - family: Space Grotesk
    #   fonts:
    #     - asset: assets/fonts/SpaceGrotesk-VariableFontWeight.ttf
    #       style: normal
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-300.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-400.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-500.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-600.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-700.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
